<?php

namespace Kulcua\ExtensionBundle\Repository;

/**
 * DateMaintenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateMaintenanceRepository extends \Doctrine\ORM\EntityRepository
{
}
