kulcua_extension:
    resource: "@KulcuaExtensionBundle/Controller/"
    type:     annotation
    prefix:   /tui

# open_loyalty_core:
#     resource: "@OpenLoyaltyCoreBundle/Resources/config/routing.yml"
