kulcua_extension:
    resource: "@KulcuaExtensionBundle/Controller/"
    type:     annotation
    prefix:   /api

# open_loyalty_core:
    # resource: "@OpenLoyaltyCoreBundle/Resources/config/routing.yml"
