warranty:
    resource: "@WarrantyBundle/Resources/config/routing.yml"

chat:
    resource: "@ChatBundle/Resources/config/routing.yml"

maintenance:
    resource: "@MaintenanceBundle/Resources/config/routing.yml"

open_loyalty_core:
    resource: "@OpenLoyaltyCoreBundle/Resources/config/routing.yml"
