services:
    _defaults:
        autowire: true
        autoconfigure: true

    kc.warranty.form_type.customer_details:
        class: Kulcua\Extension\Bundle\WarrantyBundle\Form\Type\CustomerDetailsFormType
        tags:
            - { name: form.type }

    kc.warranty.form_type.customer_address:
        class: Kulcua\Extension\Bundle\WarrantyBundle\Form\Type\CustomerAddressFormType
        tags:
            - { name: form.type }

    kc.warranty.form_type.warranty_id:
        class: Kulcua\Extension\Bundle\WarrantyBundle\Form\Type\WarrantyIdFormType
        tags:
            - { name: form.type }

    kc.warranty.form_type.customer_id:
        class: Kulcua\Extension\Bundle\WarrantyBundle\Form\Type\CustomerIdFormType
        arguments:
            - '@oloy.user.read_model.repository.customer_details'
        tags:
            - { name: form.type }

    kc.warranty.form_type.warranty:
        class: Kulcua\Extension\Bundle\WarrantyBundle\Form\Type\WarrantyFormType
        tags:
            - { name: form.type }
