Kulcua\Extension\Component\Maintenance\Domain\ReadModel\MaintenanceDetails:
  exlusion_policy: all
  properties:
    maintenanceId:
      expose: true
      inline: true
    customerId:
      expose: true
      inline: true
