services:
    Kulcua\Extension\Bundle\MaintenanceBundle\Security\Voter\MaintenanceVoter:
        arguments:
            $sellerDetailsRepository: '@oloy.user.read_model.repository.seller_details'
        tags:
            - { name: security.voter }
