jms_serializer:
    metadata:
      directories:
        Conversation:
          namespace_prefix: "Kulcua\\Extension\\Component\\Conversation\\Domain"
          path: "@ChatBundle/Resources/config/serializer"