services:
    _defaults:
        autowire: true
        autoconfigure: true

    kc.conversation.command_handler:
        class: Kulcua\Extension\Component\Conversation\Domain\Command\ConversationCommandHandler
        arguments:
            - '@kc.conversation.repository'
            - '@broadway.event_dispatcher'
        lazy: true
        tags:
            - { name: broadway.command_handler }

    Kulcua\Extension\Component\Conversation\Domain\EventSourcedConversationRepository:
        arguments:
            - '@broadway.event_store'
            - '@broadway.event_handling.event_bus'
            - ['@broadway.metadata_enriching_event_stream_decorator']

    Kulcua\Extension\Component\Conversation\Domain\ConversationRepository:
        arguments:
            - '@Kulcua\Extension\Component\Conversation\Domain\EventSourcedConversationRepository'
            - '@broadway.event_store'
            - '@OpenLoyalty\Bundle\CoreBundle\Repository\DBALSnapshotRepository'
            - '@Broadway\Snapshotting\Snapshot\Trigger\EventCountTrigger'

    kc.conversation.read_model.repository.conversation_details:
        class: 'Broadway\ReadModel\ReadModel'
        factory: ['@oloy.read_model.repository.factory', create]
        arguments:
            - 'kc.conversations_details'
            - 'Kulcua\Extension\Component\Conversation\Domain\ReadModel\ConversationDetails'
            - 'Kulcua\Extension\Component\Conversation\Infrastructure\Repository\ConversationDetailsElasticsearchRepository'

    Kulcua\Extension\Component\Conversation\Domain\ReadModel\ConversationDetailsProjector:
        tags:
            - { name: broadway.domain.event_listener }
        arguments:
            $conversationRepository: '@kc.conversation.repository'
            $repository: '@kc.conversation.read_model.repository.conversation_details'

    Kulcua\Extension\Component\Conversation\Domain\ReadModel\ConversationDetailsRepository: '@kc.conversation.read_model.repository.conversation_details'
