conversation:
    resource: "@ChatBundle/Controller/Api/ConversationController.php"
    type:     annotation
    prefix:   /api/chat

message:
    resource: "@ChatBundle/Controller/Api/MessageController.php"
    type:     annotation
    prefix:   /api/chat

message_photo:
    resource: "@ChatBundle/Controller/Api/MessagePhotoController.php"
    type:     annotation
    prefix:   /api/chat