conversation_api:
    resource: "@ChatBundle/Controller/Api/ConversationController.php"
    type:     annotation
    prefix:   /api/chat

message_api:
    resource: "@ChatBundle/Controller/Api/MessageController.php"
    type:     annotation
    prefix:   /api/chat