services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kulcua\Extension\Bundle\ChatBundle\Command\:
        resource: '../../Command'

    Kulcua\Extension\Bundle\ChatBundle\Controller\:
            resource: '../../Controller'
            tags: ['controller.service_arguments']

    kc.conversation.param_converter:
        class: Kulcua\Extension\Bundle\ChatBundle\ParamConverter\ConversationParamConverter
        tags:
            - { name: request.param_converter, priority: -2, converter: conversation_details_converter }

    kc.message.param_converter:
        class: Kulcua\Extension\Bundle\ChatBundle\ParamConverter\MessageParamConverter
        tags:
            - { name: request.param_converter, priority: -2, converter: message_details_converter }

    kc.conversation.form_handler.edit:
        class: Kulcua\Extension\Bundle\ChatBundle\Form\Handler\ConversationEditFormHandler
        arguments:
            - '@broadway.command_handling.command_bus'
            - '@doctrine.orm.entity_manager'

    kc.message.photos_filesystem:
        public: true
        class:     Gaufrette\Filesystem
        factory:   ['@knp_gaufrette.filesystem_map', get]
        arguments: ['message_photos']

    Kulcua\Extension\Bundle\ChatBundle\Service\MessagePhotoUploader:
        arguments:
            $filesystem: "@kc.message.photos_filesystem"