services:
    Kulcua\Extension\Bundle\ChatBundle\Security\Voter\ConversationVoter:
        arguments:
            $sellerDetailsRepository: '@oloy.user.read_model.repository.seller_details'
        tags:
            - { name: security.voter }
    Kulcua\Extension\Bundle\ChatBundle\Security\Voter\MessageVoter:
      arguments:
          $sellerDetailsRepository: '@oloy.user.read_model.repository.seller_details'
      tags:
          - { name: security.voter }
